default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: devel
  password: 1234
  host: localhost

development:
  <<: *default
  database: devel_tms

test:
  <<: *default
  database: devel_tms_test

production:
  primary:
    <<: *default
    database: storage/production.sqlite3
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate